# DragonMaster — 数据映射（中文版）
# item / gear / rune / skill  ID ↔ 中文名称

item_name_map = {
    "2rxJ495rm0GDn4h5OWKiyQ": "白蜡木原木",
    "CxUwQN-Me0qnNfyc207f0g": "枯疫木",
    "zm9DtUc8ieNZpWe7ioL_KA": "哥布林背包",
    "gunABauXjk6khTFVIKifoA": "银锭",
    "Y2Y48OMHukKIilN4srd7cA": "青铜锭",
    "52QCB0uSNJD0UoC21lRJvA": "宝库核心",
    "T8l7pktHUJoUuxi9mkrT7g": "宝库碎片",
    "SNCcLEdRbF7GAwSkvob6NQ": "丰盛炖菜",
    "hKYyX0vQ_pgLRAi2ugGK3w": "清水",
    "uYBo5UuEdMMdOyicMA9ikQ": "肉汤2",
    "Ng6eFNNuiU-VdxSoZtI6kA": "铁锭",
    "GHBDsEGyH5DJpTqa7xIC1w": "深渊脊骨",
    "ISwwk0SMdhURciK1Sr3i6Q": "粗兽皮",
    "Gv_wHkJnBgiXOfq0cCvggg": "白蜡木板",
    "guCjkksBOmEcLFut-VH-qg": "碎石",
    "FcnXn0Sq3OS7tJKuCRAc1A": "其他碎石",
    "TsGMyBWLNEWhBdNu21CwCA": "橡木原木",
    "qOY004ZJaEaR8DmcDqB2KA": "符文精华",
    "ukjoSEXQTWbO6zSJvP5Z4Q": "解毒药剂",
    "GC6S207zgsmHryqJEdEQaQ": "符文护甲片",
    "Dns4MEGuhT5fcRWocI5o9Q": "线",
    "DJIQWUsnDB7Umey0E2dFgA": "沼泽焦油",
    "vgsjm0jT19zFn1uH9N2Rbg": "羊毛线",
    "qRA1TEfZJkMoanWXc_l-Sg": "弱效生命药水",
    "2vSF4Se4MkWaZG0pHYcb8g": "毒牙箭",
    "D-BzgHFSHkyc53teVzmBNA": "金矿石",
    "9jFU2lh9l0qPbNTspGCBFA": "金锭",
    "GQcT3TAgK0ulDFXjsp-k1A": "布料1",
    "6kYeY05XaTnhySas_bXdnw": "布料2",
    "Jf2AM4PfnUqwTuW0cPXheA": "羊毛布",
    "-jEah0znNr-2UVmbHK-Hqg": " dwellberry浸剂",
    "1-eS15sb9UW_8kRzIMyV6g": "铁箭",
    "igveHUWYg2AeXe69EwW1PA": "凶猛浸剂",
    "cZ6va0BSo6_5Dg2Pi23lUQ": "闪避浸剂",
    "PZdR5E2sYqyUe-2JgBsCfA": "疾步浸剂",
    "u9KamEevDhDoqA-Ypsobrw": "攻击药水",
    "-9Zin0B1C7GQgVKwKSR0hQ": "生命药水",
    "ab53An3iPkyjTqnHyme-0A": "兽皮碎料",
    "3wV1xUv5zBDHRiaAk2qv7w": "磨刀石",
    "mZWtu9Ir9ECtl0a7cV7uJw": "羊毛",
    "QpxVI0bu8fcLkpuM7HrEaw": "干 dwellberry",
    "HwM2_HvXZUyt8FmT4F2iYQ": "土豆",
    "1k8-cj3JqEGeRgu1P7PK2g": "生鼠肉",
    "GHxAwJ8gNkSe3vxloWof2A": "红莓",
    "QfPOk0c4rF6PIUqOxt0ytg": "肉披萨",
    "FPYmOkCqcOpLYpaP1DKYjA": "桃子",
    "yEEiukHPM7htB4WeWEXeWg": "炒洋葱",
    "0aufkk55nHU1TlSAXZ0o3g": "烤鼠肉",
    "xawyKY4sAkmNcNuINCw3ww": "银矿石",
    "LURhZ0Q6FaLGzh-siBuT7g": "野生灵气",
    "XII5rkqVhw9I3sWWZNKteA": "狼人背包",
    "NeMd5ktRmFW1ZWqnCwsxKA": "牛腩排",
    "EHN6Hs9NFkur7chZVfchJg": "卷心菜",
    "sGZHV0IIuJLCDIyGNNBMbA": "干红莓",
    "Ua7XqsiwjUio_H540eRegw": "生野味肉",
    "O9t9Kknjb4lXvNKsNl7Vrg": "滋补汤",
    "tosPpUxp9FZgwdGvvXrcjw": "生野兽肉",
    "DQdI2EZLlP0EJB2C6_R28w": "炒卷心菜",
    "CPT7I01jfIBmhyCQLJH31A": "弱效专注工匠药水",
    "_a30PUP3vGbK6omuRTvw2Q": "柔软兽毛",
    "xAyLrEN_5B3KGXOjhpGzrg": "小型守护石",
    "rTRm3cGOmUm1h1BMEYzTwA": "铁矿石",
    "gC-ZukCFUhIWbCyJIkj3LQ": "牛排",
    "A8Lx3sZhHEeG4GXsl4ZLZw": "铜矿石",
    "u-HYwkRw-MdC8hSQnS84Vw": "中型守护石",
    "h1AqBkRETk-Fu_65W6BjVw": "锡矿石",
    "wgV3TEOkcYod4tGRdutHqg": "烤土豆",
    "8gh6wkTHrHGgAMSeSMHNTw": "弱效专注采矿药水",
    "U3WBak2LNdsGzrajcaLGpw": "弱效专注伐木药水",
    "K7le0EXS_TjIx-Wb9d9PZg": "弱效专注烹饪药水",
    "0PXPSUTx8SdrxW6J26Ljfw": "弱效专注符文药水",
    "AEnD3ErsJVZ3V7WT1YdPQQ": "鹿角",
    "6lzGokw1exVCJAmMfnUnkg": "电击植物球茎",
    "vxn3aEpxraaQXJi9Btd7Cw": "毒植物球茎",
    "OQisqk4_V81aRxSm8IjMMg": "粘土板",
    "JsMp30dRbfOXIPuy-4NmFA": "洋葱",
    "6VtTq32kQkyOk-E3Ly05-A": "生鸟肉",
    "EWuEEEhBQ59daI2TL5y9YQ": "小兽牙",
    "xhvDCkkTzJPbihGOZo3Hvw": "未烧制粘土容器",
    "Ttc6u0zyAi-JMaOjrxwtNQ": "生农场肉",
    "Br8lTU45wX65kDigZkkgAg": "燃料块",
    "z-xbJy9IS0iWNNx9WciARQ": "藤根",
    "zEg0M0VWEp6-wLOhkvYJ8A": "粘土模具",
    "tKokB0xYm6tJNHiWwmG2SQ": "灵气树皮",
    "v5MSO2Wz4ke5xOGvKC5GlQ": "羽毛",
    "uTmDj0pXttZKU7qob4UvNw": "粘土容器",
    "RdhNn0ebpZZIPQqMviMjNg": "砂岩",
    "qelCL0cKP9oFmYaJkKg6wA": "龙牙",
    "FXYVR0dXwrzmeo-goNwTHA": "未烧制粘土模具",
    "E5lUJEc3VidsqDGPkYhl4A": "公羊角",
    "qwgPgkOGqffCUdG9M7YR2Q": "熔融玻璃",
    "EK3fckHjkrHbATuNLd9Jhg": "未烧制粘土板",
    "C-Blv0bNk7v6BOWLA8Cw-g": "粘土装饰",
    "sycphkkEs4cXKKC721kS2w": "未烧制粘土装饰",
    "7MA-NkEejSNBooCvO4XI9w": "巨兽牙",
    "FaDdOe9tLUOzvrkYSPpb3Q": "橡木板",
    "_R44FI_bhEm8Gx61swlzpA": "石头",
    "GXtUfUZIYgpsYAGE4y5vEg": "研磨粘土",
    "83Kcm0CpBOcYsk-eo-dfMw": "花岗岩",
    "Cu5DREB0z4_XYRGkXu8U9A": "研磨花岗岩",
    "KejxKZhqBEy2BmyMUMidlA": "皮革",
    "UyIYrQzoTkaR04aJNXLTJQ": "硬皮革",
    "EnjZ-B1MLkuduCRe1oLNQw": "兽骨",
    "x-SiNQenZEuF0yyTPkxhiw": "木炭",
    "ehZX4E-aGmiITq6BdnbgFA": "沼泽线",
    "Rex-3ECcbilpOVqd6zWpIQ": "恐狼皮革",
    "3_luxedD0kyY_dd3UKYvEQ": "粘合剂",
    "LLV95ECQPPkItvyaC0gCzQ": "粘土"
}

gear_name_map = {
    "P3_Aq0nAXu5dlFuBNGgyaw": "深渊鞭",
    "RyuOEkWEWdGcvQqo2dPOgA": "抗龙盾",
    "_oShik-jE3kWgsG82AEuNQ": "枯疫木短弓",
    "Hcq0C0UjvN3n8q-X2uqa7w": "光之法杖",
    "YvBVZjzx_UKN9z1wIPzlrA": "铁斧",
    "VfaynRGcAkammV5YUusfbA": "铁镐",
    "lWGe1hSwiECAS9xhsMzJfg": "火把",
    "gIoZIUIT52OUDkGFuzSBlw": "荒野射手头巾",
    "fr5LJkUvJRZ-DbqVbKaB4w": "荒野射手胸甲",
    "l6qWl0-xTPdrhweMah3eTg": "荒野射手护腿",
    "71LhGUmAvrlALY6KcS8W3Q": "碎裂披风",
    "3LufGUl5SzS2zV2Vj7QCPg": "T4 毒匕首",
    "FK7SwEPmPfVFztSXScvKQA": "水晶弓",
    "s7HI6EmvRXRq7T69epFpxg": "猎人雄鹿弓",
    "hThLR2Lk6kODfRRmAs4YBQ": "铁钉头锤",
    "o9zzhev_YEulDWv5D8vI3A": "铁战锤",
    "h0jHf-hTx0KeGyukdCnN4Q": "巫师帽",
    "2-okKxsy7k-FRgP-vgQEQA": "巫师袍",
    "FlnNkilo_EyfB0gbqf32AQ": "巫师护腿",
    "h3G7NqBW-0i6TrNRlBD6Sg": "学徒帽",
    "g9vfX7KsMkurrMZa7z1aPg": "学徒袍",
    "AIZLP8mwfEij7hwWUOr-aQ": "学徒护腿",
    "lhrErX7MF0q9XlhdPdhCrA": "青铜头盔",
    "N2kAI3uQgki-eP0rIoHYhQ": "青铜胸甲",
    "wQPcKK1XV0iF1_CADXUwEw": "青铜护腿",
    "PxHJuE6PgUKY-zugyUXSUQ": "铁头盔",
    "CAtRgsni70SltXq4uzs6Yg": "铁胸甲",
    "lWABtugu90SEqpE70Gf8ew": "铁护腿",
    "GutTdkwskIsX75i6-CilJA": "龙族法师兜帽",
    "rXtN2EZOq9NpnL-WyVpF8Q": "龙族法师袍",
    "uDBybUNuv5UipiSXb8BG-A": "龙族法师护腿",
    "5PEcXkJHZY9PDqKb9Skqww": "圣骑士头盔",
    "0LL6JE9-pi2e3VSDOwqqYw": "圣骑士胸甲",
    "mkSObERGptKuVly00uIfTQ": "圣骑士护腿",
    "YvIen0_ZFiR1Kn-5ucQrDA": "强化头盔",
    "mkaB7UQN1fBbSkGNVTVRZw": "强化胸甲",
    "GZuI4kHd7c-hpqWq5Nbdpw": "强化护腿",
    "wLzThnOQEUaw90mBnn8QTw": "硬皮头巾",
    "h7tqvcgrDk2iGdD7TYwiSA": "硬皮胸甲",
    "7Ajx5nOVUUW6l8nU2YiLOA": "硬皮护腿",
    "YVvQRk9Uv1a4PceWi3985w": "钉皮头巾",
    "eAqy2E05wXWCK4O5s2Dnwg": "钉皮胸甲",
    "bZAEoUISHmuQXu6HlIFIyQ": "钉皮护腿",
    "-mOez0ZysUa2kkuZQY4s0w": "皮头巾",
    "Q6DUGmTWNkG5S1Ki_5Nz1w": "皮护腿",
    "XT0Zft6J30iLvjVNxnzw6Q": "皮胸甲",
    "FK7SwEPmPfVFztSXScvKQA": "水晶弓",
    "ARf7DUYPa_AlyLOOsnTIYw": "领主之威",
    "9QZ0eUU7xVxKhq-_nMoCcQ": "暗黑法师袍",
    "hWGilEcAZgtX2JWejH4ncA": "暗黑法师护腿",
    "M3Y6KEIGYrsnS8-j5ewQxw": "暗黑法师兜帽",
    "3LufGUl5SzS2zV2Vj7QCPg": "T4 毒匕首",
    "NA76rEFl7Di8f5aFj_L3SA": "T3 毒匕首",
    "924KFU8kvGNESi-zN0doDw": "白蜡木战斗法杖",
    "s7HI6EmvRXRq7T69epFpxg": "猎人雄鹿弓",
    "ALn1jUyxkFwgIHmHAGkoxg": "龙族法杖",
    "hS_GuEyi70Xf932m1rq7PA": "悲月法杖",
    "GO-fJEIf4N7Y0EeG5D0YSw": "T2 燃烧匕首",
    "CN1GVEgi8t_uRs-yFmH_FQ": "T4 燃烧匕首",
    "g7aQPfflM0q63qyJZyWI8w": "橡木短弓",
    "NqTlRkd7Zw4BE9GM_mDbtw": "荒野斥候短弓",
    "IJILMByu-kCq_0feZkzKBw": "石棒",
    "o9zzhev_YEulDWv5D8vI3A": "铁战锤",
    "yvkI8EKmmaD8zT-a7IVqOA": "枯疫木战斗法杖",
    "8ivfA0axvgaP1smick68pw": "橡木战斗法杖",
    "lJqTrE_r-nkdhwyoPhfsAA": "青铜钉头锤",
    "OJSTGEEY6uNu4beRiM4Qvw": "哥布林挥砍刃",
    "djtTEkaTg3ARdre_xsNXCg": "骨棒",
    "VVq58NyN8EKOk3WUg2130Q": "冒险者长弓",
    "eqrPvUI8qhvjnbGRoIxNug": "青铜剑",
    "lHKVrkMlSsZx5lKVZRH63Q": "酋长之刃",
    "gFA3V8-Y5UGLPAtJKYNnTw": "铁剑",
    "UW6yfU2tUde27I2aZB9JHA": "T2 毒匕首",
    "-ahw20RwuJqFDsKcOrryNQ": "T4 流血匕首",
    "P4DqJ03JPXW9Uf-z9vf9cA": "T1 燃烧匕首",
    "f5pdM9IkUU2dZp0okjecuA": "石匕首",
    "AQ-JQEAJEyOWJKuGTq7KCQ": "T2 流血匕首",
    "yte2PUYaqeYZH02J_aviEg": "花岗岩重锤",
    "jWfoPkWonpdDzBWYUQ1qPg": "T3 流血匕首",
    "UBB8W0_AMoWP5yKf7M9KRw": "橡木长弓",
    "4bMdm0gvxNqxKSaQjGtFmQ": "屠龙匕首",
    "pmx4j0E3SP9r4gmY38QrYA": "T1 电击匕首",
    "PPvgBkmqKmyUwki-TAtqig": "T3 电击匕首",
    "d-s3s5ciWkSi_Q4p-XaMoA": "铁巨斧",
    "PSWEV0JzVwxsalWCFqPbOw": "青铜巨剑",
    "XWOefkcc3bliVpWrsPMokg": "裂颅者"
}

rune_name_map = {
    "Dvo6TE2d7YNnoni8XbKYzw": "空气符文",
    "bbLdJRhwPEWt1ScENYRUCg": "水符文",
    "lCE7i3iXGUuHv7FphIOcXg": "大地符文",
    "_QMgbMYhjU-9jAD_euFbyQ": "火焰符文",
    "iKbF7k2XvufGqqyg5rK-vQ": "自然符文",
    "_c9JTkwKy8s88GWv586hbQ": "秩序符文",
    "4wdYZE-FFMhS9Iia0ftWDg": "星界符文"
}

skill_name_map = {
    "Wf3i7Ha-B06DH719j1vtBw": "工匠",
    "4pefO9k1lUqfA6mvHNi1SA": "攻击",
    "waK-8EyQFQ2xEjCGYmuTRQ": "建造",
    "Tn7t6DQyX0-Q0cM5K7B90A": "烹饪",
    "0hreSMRVXUihq9qjDO2CFA": "魔法/远程",
    "jqX0Gh6QI0GFFPCDFK_CJQ": "采矿",
    "heq7u88Q2UuLXFqLGTVwQw": "魔法/远程",
    "NOqC-z-2ckqi0El22qMFlw": "符文工艺",
    "4zYUGF5u_0KbMLkWJmmBbQ": "伐木"
}

# 合并映射（item + gear）
combined_map = {**item_name_map, **gear_name_map}

# 排序后的中文名称列表
regular_items = ["空"] + sorted(item_name_map.values())
gear_items     = ["空"] + sorted(gear_name_map.values())
rune_items     = ["空"] + sorted(rune_name_map.values())
